language: python
sudo: false

services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2-precise
    packages:
    - mongodb-org-server

python:
  - 3.4
  - 3.5

before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
  - "export DISPLAY=:99.0"
  - git clone https://github.com/nsls-ii/nsls2-ci ~/scripts
  - . ~/scripts/install-miniconda.sh
  - . ~/scripts/init-filestore.sh
  - . ~/scripts/init-metadatastore.sh

install:
  - conda create -n testenv nose pip python=$TRAVIS_PYTHON_VERSION scipy requests matplotlib jsonschema traitlets pytest coverage event-model metadatastore databroker ophyd historydict boltons doct toolz tifffile pymongo pcaspy pyepics readline super_state_machine cycler xray-vision lmfit jinja2 -c conda-forge
  - source activate testenv
  - pip install codecov
  - python setup.py install
  # Need to clean the python build directory (and other cruft) or pytest is
  # going to find the build directory and get confused why there are two sets
  # of every test file
  - python -c "from filestore import utils, conf; utils.install_sentinels(conf.connection_config, 1)"
  - git clean -xfd

script:
  - coverage run run_tests.py
  - coverage report -m

after_success:
  - codecov
